// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/helloservice.proto

package hipstershop

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Helloservice service

func NewHelloserviceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Helloservice service

type HelloserviceService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
}

type helloserviceService struct {
	c    client.Client
	name string
}

func NewHelloserviceService(name string, c client.Client) HelloserviceService {
	return &helloserviceService{
		c:    c,
		name: name,
	}
}

func (c *helloserviceService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Helloservice.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Helloservice service

type HelloserviceHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
}

func RegisterHelloserviceHandler(s server.Server, hdlr HelloserviceHandler, opts ...server.HandlerOption) error {
	type helloservice interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
	}
	type Helloservice struct {
		helloservice
	}
	h := &helloserviceHandler{hdlr}
	return s.Handle(s.NewHandler(&Helloservice{h}, opts...))
}

type helloserviceHandler struct {
	HelloserviceHandler
}

func (h *helloserviceHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.HelloserviceHandler.Call(ctx, in, out)
}
